### ISSUE TITLE
Pulseq dependency

### ISSUE THREAD

**Issue by J-Endres** [MRsources/MRzero-Core#16]
Core works with pulseq up to the newest dev version. We should not hardcode the pypulseq version in the dependencies like we do it now, so the user can install any pulseq version, installing mr0 core afterwards should not overwrite it.

**Comment by btasdelen** [comment]
Hi @J-Endres, piggybacking on this issue rather than creating a new one, as my issue is caused by the same problem.

Right now, I can not `pip install mrzerocore` in a PyPulseq project as it conflicts with higher version of PyPulseq. Would making the dependency `pypulseq>=1.3.1.post1`, rather than `pypulseq==1.3.1.post1` solve the issue?

**Comment by J-Endres** [comment]
This is solved in the branch `dev-v0.2.6`.

Closing this for now, if version 0.2.6 is released and this problem persists, please re-open
