### ISSUE TITLE
spiral TSE seq file not properly simulating

### ISSUE THREAD

**Issue by mzaiss** [MRsources/MRzero-Core#19]
[spiralTSE.seq.txt](https://github.com/MRsources/MRzero-Core/files/13393700/spiralTSE.seq.txt)

create from

https://github.com/HennigJue/single-shot-spiral-TSE

![grafik](https://github.com/MRsources/MRzero-Core/assets/8328474/c515bec2-3a07-41b9-8e34-04f3ff4f6c9e)

**Comment by J-Endres** [comment]
## 1. The importer doesn't know the pulse usage
The plotted k-space (as well as the reconstruction) needs to know which pulses are used for refocusing and which for excitation.
This is guessed using the flip angle, assuming that all pulses > 90° are for refocusation. The spiral TSE sequence uses lower flip angles, so when calculating the k-space trajectory some pulses are wrongly accused to be excitation pulses.

Fix, insert after loading the sequence:
```python
for rep in seq0[3:]:
    rep.pulse.usage = mr0.PulseUsage.REFOC
```

After that, the readout is centered correctly (doesn't change the simulation which always considers all paths):
![image](https://github.com/MRsources/MRzero-Core/assets/67545816/ae6d7ed7-0c4c-4b38-91c6-0424fd428e40)

## 2. Wrong gradients
This has still to be investigated: The spiral doesn't look very homogeneous. But more important: z-gradients seem to be wrong

![image](https://github.com/MRsources/MRzero-Core/assets/67545816/004328ec-4dcd-4e73-b898-40c3c919486e)

The simulation generates no signal because only a single slice is simulated, where magnetization is spoiled because the readout trajectory is not on z=0

**Comment by mzaiss** [comment]
ok, i try to recreate the seq files without z grad

**Comment by J-Endres** [comment]
The new importer in mr0 v2.6 will solve this, closing this issue

**Comment by mzaiss** [comment]
proof:
![grafik](https://github.com/MRsources/MRzero-Core/assets/8328474/153c80c7-130f-4f19-b83a-12b6e11725c9)
![grafik](https://github.com/MRsources/MRzero-Core/assets/8328474/90d1ed4f-eec0-476b-8831-1dbc6f0a4f62)
